<a href="https://colab.research.google.com/github/ritika-sharma013/numpy_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
print(np.version)

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>


***Experimenting with numpy ***

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([[1.0,2.0,3.0], [4,5,6]])

print(a)
print(b)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# get dimensions - tells
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
a.shape

(5,)

In [ ]:
b.shape

(2, 3)

In [ ]:
# size - n*m
a.size

5

In [ ]:
b.size

6

In [ ]:
# data type
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
c= np.array([[2.134, 3.121, 4.111], [5.993, 6.123, 2.345]])
print(c)

[[2.134 3.121 4.111]
 [5.993 6.123 2.345]]


In [ ]:
c.dtype

dtype('float64')

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.